# Generated by cli/scripts/render-formula.sh for cli-v0.2.0 — do not edit.
class Bea < Formula
  desc "Beancount.io CLI: check, query, report on, and edit beancount ledgers"
  homepage "https://beancount.io"
  url "https://files.pythonhosted.org/packages/10/2a/19396d89f67597dab60c97ef22cd12004033129687be4d8ce7b6eee4e69d/beancount_io-0.2.0.tar.gz"
  version "0.2.0"
  sha256 "039651ce0e82f2b73220b74f2f892024e19e89dccae3496dfdf0355b4b349fcc"
  license all_of: ["MIT", "GPL-2.0-only"]

  depends_on "python@3.12"
  # Not `=> :build`: post_install needs uv too, and a build-only dependency is
  # what `brew autoremove` would take away first.
  depends_on "uv"

  def install
    project = libexec/"project"
    project.install "pyproject.toml", "README.md", "LICENSE", "NOTICE.fava", "requirements.lock", "engine-requirements.lock", "engine-optional-beangulp.lock", "engine-optional-beanprice.lock", "src", "LICENSE.engine"
    (project/"scripts").install "scripts/build_hook.py"

    uv = Formula["uv"].opt_bin/"uv"
    system uv, "venv", "--python", Formula["python@3.12"].opt_bin/"python3.12", libexec/"venv"
    # bea itself is pure Python, so it is safe to install before Homebrew's
    # relocation pass — and installing it here is what makes bin/bea a real
    # file at the moment the keg is linked.
    system uv, "pip", "install", "--python", libexec/"venv/bin/python", "--no-deps", project
    # Point bea at the keg-local engine so local commands never look for a
    # global bean-* tool or download on first use.
    (bin/"bea").write <<~EOS
      #!/bin/bash
      export BEA_ENGINE_DIR="#{libexec}/engine"
      exec "#{libexec}/venv/bin/bea" "$@"
    EOS
    pkgshare.install "scripts/smoke-installed.py"
    pkgshare.install "docs/examples/csv_importers.py"
  end

  # The dependency tree lands after Homebrew has rewritten the dylib IDs of
  # every Mach-O file in the keg. That pass cannot lengthen the install name
  # inside a prebuilt wheel — there is no header padding for the longer path —
  # and pydantic-core's extension module fails it, which is fatal to
  # `brew install`. Wheels are the entire point of this formula (no Rust
  # toolchain, no source builds on a user's machine), so they arrive here,
  # after that pass has already run. --require-hashes pins every one of them to
  # the exact artifact the release tested.
  def post_install
    uv = Formula["uv"].opt_bin/"uv"
    system uv, "pip", "install",
           "--python", libexec/"venv/bin/python",
           "--require-hashes", "--only-binary", ":all:", "--requirement", libexec/"project/requirements.lock"
    # Separate engine environment (ADR014): relocatable so console-script
    # shebangs survive any keg move; only hash-pinned upstream packages go here.
    system uv, "venv", "--relocatable", "--python", Formula["python@3.12"].opt_bin/"python3.12", libexec/"engine"
    system uv, "pip", "install",
           "--python", libexec/"engine/bin/python",
           "--require-hashes", "--only-binary", ":all:", "--requirement", libexec/"project/engine-requirements.lock"
  end

  test do
    assert_match "bea #{version}", shell_output("#{bin}/bea --version")
    system libexec/"venv/bin/python", pkgshare/"smoke-installed.py", bin/"bea", "--installed"
  end
end
