# Generated by cli/scripts/render-formula.sh for cli-v0.1.0 — do not edit.
class Bea < Formula
  desc "Beancount.io CLI: check, query, report on, and edit beancount ledgers"
  homepage "https://beancount.io"
  url "https://files.pythonhosted.org/packages/source/b/beancount-io/beancount_io-0.1.0.tar.gz"
  version "0.1.0"
  sha256 "5ca75fd0a3effa7f21b04694dd50f7589417771b09e3581758e5dbca359c062c"
  license "MIT"

  depends_on "python@3.12"
  # Not `=> :build`: post_install needs uv too, and a build-only dependency is
  # what `brew autoremove` would take away first.
  depends_on "uv"

  def install
    project = libexec/"project"
    project.install "pyproject.toml", "README.md", "requirements.lock", "src"

    uv = Formula["uv"].opt_bin/"uv"
    system uv, "venv", "--python", Formula["python@3.12"].opt_bin/"python3.12", libexec/"venv"
    # bea itself is pure Python, so it is safe to install before Homebrew's
    # relocation pass — and installing it here is what makes bin/bea a real
    # file at the moment the keg is linked.
    system uv, "pip", "install", "--python", libexec/"venv/bin/python", "--no-deps", project
    bin.install_symlink libexec/"venv/bin/bea"
    pkgshare.install "scripts/smoke-installed.py"
    pkgshare.install "docs/examples/csv_importers.py"
  end

  # The dependency tree lands after Homebrew has rewritten the dylib IDs of
  # every Mach-O file in the keg. That pass cannot lengthen the install name
  # inside a prebuilt wheel — there is no header padding for the longer path —
  # and pydantic-core's extension module fails it, which is fatal to
  # `brew install`. Wheels are the entire point of this formula (no Rust
  # toolchain, no source builds on a user's machine), so they arrive here,
  # after that pass has already run. --require-hashes pins every one of them to
  # the exact artifact the release tested.
  def post_install
    system Formula["uv"].opt_bin/"uv", "pip", "install",
           "--python", libexec/"venv/bin/python",
           "--require-hashes", "--only-binary", ":all:", "--requirement", libexec/"project/requirements.lock"
  end

  test do
    assert_match "bea #{version}", shell_output("#{bin}/bea --version")
    system libexec/"venv/bin/python", pkgshare/"smoke-installed.py", bin/"bea"
  end
end
