# Generated by scripts/bex-cli-formula.sh for bex-cli/v0.3.0 — do not edit.
class Bex < Formula
  desc "Bex CLI: Render-compatible command line for the Bex platform"
  homepage "https://github.com/bex-co/bex"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/bex-co/bex/releases/download/bex-cli%2Fv0.3.0/bex-0.3.0-darwin-arm64.tar.gz"
      sha256 "bacaf1e726efe167ee82acb4a83f9ffa4bc96ef1568b852cc6748ac8e4509655"
    end
    on_intel do
      url "https://github.com/bex-co/bex/releases/download/bex-cli%2Fv0.3.0/bex-0.3.0-darwin-amd64.tar.gz"
      sha256 "03aef7fcc86a36a6c48f00def776d9ac9af682e5c84c162e375a8cd6e553a538"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/bex-co/bex/releases/download/bex-cli%2Fv0.3.0/bex-0.3.0-linux-arm64.tar.gz"
      sha256 "7b0f3cf71714f2dab2a15eb3ac437394cf1bc5cd4a05ba00fa17845f7a7b4532"
    end
    on_intel do
      url "https://github.com/bex-co/bex/releases/download/bex-cli%2Fv0.3.0/bex-0.3.0-linux-amd64.tar.gz"
      sha256 "24be390cd4a183b18a649c4c8a06d14c0eb3f65909aa40bc663ea0a8d9bce0be"
    end
  end

  def install
    # Homebrew strips a sole top-level archive directory during staging, so
    # the binary is usually at the root; fall back to the nested layout.
    bin.install(File.exist?("bex") ? "bex" : Dir["bex-*/bex"].fetch(0))
  end

  test do
    assert_match "bex v#{version}", shell_output("#{bin}/bex --version")
  end
end
