# Generated by scripts/bex-cli-formula.sh for bex-cli/v0.2.1 — do not edit.
class Bex < Formula
  desc "Bex CLI: Render-compatible command line for the Bex platform"
  homepage "https://github.com/bex-co/bex"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/bex-co/bex/releases/download/bex-cli%2Fv0.2.1/bex-0.2.1-darwin-arm64.tar.gz"
      sha256 "650ba4e85693086fa07f98bcde1c461d32d03f06bd18273a6697bbbab6e6c2a2"
    end
    on_intel do
      url "https://github.com/bex-co/bex/releases/download/bex-cli%2Fv0.2.1/bex-0.2.1-darwin-amd64.tar.gz"
      sha256 "9a83996c88f93897e830d75591fb285e9c0c0db8189dd0acde23106d855cb9f2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/bex-co/bex/releases/download/bex-cli%2Fv0.2.1/bex-0.2.1-linux-arm64.tar.gz"
      sha256 "1b2e0ae81f583d93f0388b88d7ed008e186473fb7754fbc7c5a9a7dfee5633a8"
    end
    on_intel do
      url "https://github.com/bex-co/bex/releases/download/bex-cli%2Fv0.2.1/bex-0.2.1-linux-amd64.tar.gz"
      sha256 "185dda1796b2ddfc17960612ccb5eedf2f9be4bca144d22d4d809f319371c5fe"
    end
  end

  def install
    # Homebrew strips a sole top-level archive directory during staging, so
    # the binary is usually at the root; fall back to the nested layout.
    bin.install(File.exist?("bex") ? "bex" : Dir["bex-*/bex"].fetch(0))
  end

  test do
    assert_match "bex v#{version}", shell_output("#{bin}/bex --version")
  end
end
