# Generated by scripts/bex-cli-formula.sh for bex-cli/v0.1.0 — do not edit.
class Bex < Formula
  desc "Bex CLI: Render-compatible command line for the Bex platform"
  homepage "https://github.com/bex-co/bex"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/bex-co/bex/releases/download/bex-cli%2Fv0.1.0/bex-0.1.0-darwin-arm64.tar.gz"
      sha256 "9a322c452cbd8eebbae6559f1a202abd03960e00c40f6a483c1530b73473b6a2"
    end
    on_intel do
      url "https://github.com/bex-co/bex/releases/download/bex-cli%2Fv0.1.0/bex-0.1.0-darwin-amd64.tar.gz"
      sha256 "6ef20c8a835ae48304cebeb44a26dbaaaa91099a1b48b171f30262b3a9c80cd4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/bex-co/bex/releases/download/bex-cli%2Fv0.1.0/bex-0.1.0-linux-arm64.tar.gz"
      sha256 "3b2a15abef68addc459fed6b541077bf678520392df34249f873d9a003e842d6"
    end
    on_intel do
      url "https://github.com/bex-co/bex/releases/download/bex-cli%2Fv0.1.0/bex-0.1.0-linux-amd64.tar.gz"
      sha256 "9b403965394a4b07e94305f7dbc485bebd91eb2d9052be9b8c78c76515707dd9"
    end
  end

  def install
    bin.install Dir["bex-*/bex"].first => "bex"
  end

  test do
    assert_match "bex v#{version}", shell_output("#{bin}/bex --version")
  end
end
